title: Books
description: Collection of highlights from the books I have read over the years
url: "https://books.sayan.ee"
markdown: kramdown
permalink: /:title
tag_mapping:
  1: "excellence"
  2: "spirituality"
  3: "fiction"
  4: "biography"
  5: "business"
  6: "anthropology"
  7: "parenting"
  8: "relationships"
